export const components = [
  {
    type: "CPU",
    name: "AMD Ryzen 7 9800X3D",
    image: "/images/parts/cpu/9800X3D.jpg",
    cores: "8C, 16T",
    clock: "4.7GHz, 5.2GHz Boost",
    architecture: "AM5",
    tdp: "120W",
    graphics: "Radeon",
    retailers: [
      { site: "Amazon", priceCents: 47999 },
      { site: "Newegg", priceCents: 47999 },
      { site: "Micro Center", priceCents: 47999 },
      { site: "BestBuy", priceCents: 47999 },
    ],
  },
  {
    type: "CPU",
    name: "AMD Ryzen 7 9700X",
    image: "/images/parts/cpu/9700X.jpg",
    cores: "8C, 16T",
    clock: "3.8GHz, 5.5GHz Boost",
    architecture: "AM5",
    tdp: "65W",
    graphics: "Radeon",
    retailers: [
      { site: "Amazon", priceCents: 27999 },
      { site: "Newegg", priceCents: 27999 },
      { site: "Micro Center", priceCents: 27999 },
      { site: "BestBuy", priceCents: 27999 },
    ],
  },
  {
    type: "CPU",
    name: "AMD Ryzen 5 9600X",
    image: "/images/parts/cpu/9600X.jpg",
    cores: "6C, 12T",
    clock: "3.9GHz, 5.4GHz Boost",
    architecture: "AM5",
    tdp: "65W",
    graphics: "Radeon",
    retailers: [
      { site: "Amazon", priceCents: 17999 },
      { site: "Newegg", priceCents: 17999 },
      { site: "Micro Center", priceCents: 17999 },
      { site: "BestBuy", priceCents: 17999 },
    ],
  },
  {
    type: "CPU",
    name: "Intel Core Ultra 9 285K",
    image: "/images/parts/cpu/285K.jpg",
    cores: "6C, 12T",
    clock: "3.9GHz, 5.4GHz Boost",
    architecture: "AM5",
    tdp: "65W",
    graphics: "Radeon",
    retailers: [
      { site: "Amazon", priceCents: 52999 },
      { site: "Newegg", priceCents: 52999 },
      { site: "Micro Center", priceCents: 52999 },
      { site: "BestBuy", priceCents: 52999 },
    ],
  },
  {
    type: "CPU",
    name: "Intel Core Ultra 7 265K",
    image: "/images/parts/cpu/265K.jpg",
    cores: "6C, 12T",
    clock: "3.9GHz, 5.4GHz Boost",
    architecture: "AM5",
    tdp: "65W",
    graphics: "Radeon",
    retailers: [
      { site: "Amazon", priceCents: 25999 },
      { site: "Newegg", priceCents: 25999 },
      { site: "Micro Center", priceCents: 25999 },
      { site: "BestBuy", priceCents: 25999 },
    ],
  },
  {
    type: "CPU",
    name: "Intel Core Ultra 5 245K",
    image: "/images/parts/cpu/245K.jpg",
    cores: "6C, 12T",
    clock: "3.9GHz, 5.4GHz Boost",
    architecture: "AM5",
    tdp: "65W",
    graphics: "Radeon",
    retailers: [
      { site: "Amazon", priceCents: 23999 },
      { site: "Newegg", priceCents: 23999 },
      { site: "Micro Center", priceCents: 23999 },
      { site: "BestBuy", priceCents: 23999 },
    ],
  },
];
