export const components = [
  // ------------------ CPU ------------------
  {
    type: "CPU",
    name: "AMD Ryzen 7 9800X3D",
    image: "/images/parts/cpu/9800X3D.jpg",
    cores: "8C, 16T",
    clock: "4.7GHz, 5.2GHz Boost",
    socket: "AMD",
    power: 120,
    graphics: "Radeon",
    retailers: [
      { site: "Amazon", priceCents: 47999 },
      { site: "Newegg", priceCents: 47999 },
      { site: "Micro Center", priceCents: 47999 },
      { site: "BestBuy", priceCents: 47999 },
    ],
  },
  {
    type: "CPU",
    name: "AMD Ryzen 7 9700X",
    image: "/images/parts/cpu/9700X.jpg",
    cores: "8C, 16T",
    clock: "3.8GHz, 5.5GHz Boost",
    socket: "AMD",
    power: 65,
    graphics: "Radeon",
    retailers: [
      { site: "Amazon", priceCents: 27999 },
      { site: "Newegg", priceCents: 27999 },
      { site: "Micro Center", priceCents: 27999 },
      { site: "BestBuy", priceCents: 27999 },
    ],
  },
  {
    type: "CPU",
    name: "AMD Ryzen 5 9600X",
    image: "/images/parts/cpu/9600X.jpg",
    cores: "6C, 12T",
    clock: "3.9GHz, 5.4GHz Boost",
    socket: "AMD",
    power: 65,
    graphics: "Radeon",
    retailers: [
      { site: "Amazon", priceCents: 17999 },
      { site: "Newegg", priceCents: 17999 },
      { site: "Micro Center", priceCents: 17999 },
      { site: "BestBuy", priceCents: 17999 },
    ],
  },
  {
    type: "CPU",
    name: "Intel Core Ultra 9 285K",
    image: "/images/parts/cpu/285K.jpg",
    cores: "24C, 24T",
    clock: "4.6GHz, 5.7GHz Boost",
    socket: "Intel",
    power: 125,
    graphics: "Intel Xe",
    retailers: [
      { site: "Amazon", priceCents: 52999 },
      { site: "Newegg", priceCents: 52999 },
      { site: "Micro Center", priceCents: 52999 },
      { site: "BestBuy", priceCents: 52999 },
    ],
  },
  {
    type: "CPU",
    name: "Intel Core Ultra 7 265K",
    image: "/images/parts/cpu/265K.jpg",
    cores: "20C, 20T",
    clock: "4.6GHz, 5.5GHz Boost",
    socket: "Intel",
    power: 125,
    graphics: "Intel Xe",
    retailers: [
      { site: "Amazon", priceCents: 25999 },
      { site: "Newegg", priceCents: 25999 },
      { site: "Micro Center", priceCents: 25999 },
      { site: "BestBuy", priceCents: 25999 },
    ],
  },
  {
    type: "CPU",
    name: "Intel Core Ultra 5 245K",
    image: "/images/parts/cpu/245K.jpg",
    cores: "14C, 14T",
    clock: "4.6GHz, 5.2GHz Boost",
    socket: "Intel",
    power: 125,
    graphics: "Intel Xe",
    retailers: [
      { site: "Amazon", priceCents: 23999 },
      { site: "Newegg", priceCents: 23999 },
      { site: "Micro Center", priceCents: 23999 },
      { site: "BestBuy", priceCents: 23999 },
    ],
  },

  // ------------------ CPU Coolers ------------------
  {
    type: "CPU Cooler",
    name: "Thermalright Peerless Assassin 120 SE",
    liquid: false,
    size: 155,
    image: "/images/parts/cooler/thermalright.jpg",
    retailers: [
      { site: "Amazon", priceCents: 3499 },
      { site: "Micro Center", priceCents: 4999 },
    ],
  },
  {
    type: "CPU Cooler",
    name: "Noctua NH-D15",
    liquid: false,
    size: 165,
    image: "/images/parts/cooler/noctuaD15.jpg",
    retailers: [
      { site: "Amazon", priceCents: 12994 },
      { site: "Newegg", priceCents: 10878 },
      { site: "Micro Center", priceCents: 12999 },
    ],
  },
  {
    type: "CPU Cooler",
    name: "Noctua NH-L9(A/I)",
    liquid: false,
    size: 37,
    image: "/images/parts/cooler/noctuaL9.jpg",
    retailers: [
      { site: "Amazon", priceCents: 5999 },
      { site: "Newegg", priceCents: 6249 },
      { site: "Micro Center", priceCents: 6499 },
    ],
  },
  {
    type: "CPU Cooler",
    name: "ARCTIC Liquid Freezer III Pro",
    liquid: true,
    size: 360,
    image: "/images/parts/cooler/arctic360.jpg",
    retailers: [
      { site: "Amazon", priceCents: 8499 },
      { site: "Newegg", priceCents: 10999 },
      { site: "Micro Center", priceCents: 12999 },
    ],
  },
  {
    type: "CPU Cooler",
    name: "NZXT Kraken 240",
    liquid: true,
    size: 240,
    image: "/images/parts/cooler/kraken240.jpg",
    retailers: [
      { site: "Amazon", priceCents: 13999 },
      { site: "Newegg", priceCents: 14299 },
    ],
  },
  {
    type: "CPU Cooler",
    name: "Cooler Master MasterLiquid 360L Core ARGB",
    liquid: true,
    size: 360,
    image: "/images/parts/cooler/cm360.jpg",
    retailers: [
      { site: "Amazon", priceCents: 11999 },
      { site: "Newegg", priceCents: 12199 },
    ],
  },

  // ------------------ Motherboards ------------------
  // AMD
  {
    type: "Motherboard",
    name: "Asus B650E MAX GAMING WIFI ATX",
    socket: "AMD",
    size: "ATX",
    wifi: "Yes",
    image: "/images/parts/motherboard/amdATX.jpg",
    retailers: [
      { site: "Amazon", priceCents: 16899 },
      { site: "Newegg", priceCents: 17999 },
    ],
  },
  {
    type: "Motherboard",
    name: "Gigabyte B850M GAMING X WIFI6E MATX",
    socket: "AMD",
    size: "MATX",
    wifi: "Yes",
    image: "/images/parts/motherboard/amdMATX.jpg",
    retailers: [
      { site: "Amazon", priceCents: 14999 },
      { site: "Newegg", priceCents: 15299 },
    ],
  },
  {
    type: "Motherboard",
    name: "ASRock B850I Lightning WiFi Mini ITX",
    socket: "AMD",
    size: "ITX",
    wifi: "Yes",
    image: "/images/parts/motherboard/amdITX.jpg",
    retailers: [
      { site: "Amazon", priceCents: 29999 },
      { site: "Newegg", priceCents: 30499 },
    ],
  },
  // Intel
  {
    type: "Motherboard",
    name: "MSI MAG Z890 TOMAHAWK WIFI ATX",
    socket: "Intel",
    size: "ATX",
    wifi: "Yes",
    image: "/images/parts/motherboard/intelATX.jpg",
    retailers: [
      { site: "Amazon", priceCents: 23999 },
      { site: "Newegg", priceCents: 23999 },
    ],
  },
  {
    type: "Motherboard",
    name: "Gigabyte Z890M AORUS ELITE WIFI7 ICE MATX",
    socket: "Intel",
    size: "MATX",
    wifi: "Yes",
    image: "/images/parts/motherboard/intelMATX.jpg",
    retailers: [
      { site: "Amazon", priceCents: 16999 },
      { site: "Newegg", priceCents: 16999 },
      { site: "Micro Center", priceCents: 23999 },
    ],
  },
  {
    type: "Motherboard",
    name: "Asus ROG STRIX B860-I GAMING WIFI Mini ITX",
    socket: "Intel",
    size: "ITX",
    wifi: "Yes",
    image: "/images/parts/motherboard/intelITX.jpg",
    retailers: [
      { site: "Amazon", priceCents: 19999 },
      { site: "Newegg", priceCents: 19499 },
    ],
  },

  // ------------------ Memory (DDR5) ------------------
  {
    type: "Memory",
    name: "Corsair Vengeance RGB 32GB DDR5 6000MHz",
    size: "32GB",
    speed: "DDR5-60000MHz",
    image: "/images/parts/memory/corsair32.jpg",
    retailers: [
      { site: "Amazon", priceCents: 11499 },
      { site: "Newegg", priceCents: 10599 },
      { site: "Best Buy", priceCents: 11499 },
      { site: "Best Buy", priceCents: 10999 },
    ],
  },
  {
    type: "Memory",
    name: "TEAMGROUP T-Create Expert 32 GB DDR5 6000MHz",
    size: "32GB",
    speed: "DDR5-6000MHz",
    image: "/images/parts/memory/team32.jpg",
    retailers: [
      { site: "Amazon", priceCents: 9999 },
      { site: "Newegg", priceCents: 9999 },
      { site: "Micro Center", priceCents: 9999 },
    ],
  },
  {
    type: "Memory",
    name: "G.Skill Trident Z5 RGB DDR5 64GB 6400MHz",
    size: "64GB",
    speed: "DDR5-6400MHz",
    image: "/images/parts/memory/gskill64.jpg",
    retailers: [
      { site: "Amazon", priceCents: 11499 },
      { site: "Newegg", priceCents: 10599 },
      { site: "Best Buy", priceCents: 11499 },
      { site: "Best Buy", priceCents: 10999 },
    ],
  },
  {
    type: "Memory",
    name: "Crucial Classic DDR5 32GB 5600MHz",
    size: "16GB",
    speed: "DDR5-5600MHz",
    image: "/images/parts/memory/crucial16.jpg",
    retailers: [{ site: "Amazon", priceCents: 6498 }],
  },
  {
    type: "Memory",
    name: "Kingston FURY Beast DDR5 16GB 5200MHz",
    size: "16GB",
    speed: "DDR5-5200MHz",
    image: "/images/parts/memory/kingston16.jpg",
    retailers: [
      { site: "Amazon", priceCents: 5999 },
      { site: "Newegg", priceCents: 5999 },
    ],
  },
  {
    type: "Memory",
    name: "Corsair Vengeance DDR5 128GB 6400MHz",
    size: "128GB",
    speed: "DDR5-6400MHz",
    image: "/images/parts/memory/corsair128.jpg",
    retailers: [
      { site: "Amazon", priceCents: 33999 },
      { site: "Newegg", priceCents: 35999 },
    ],
  },

  // ------------------ Storage ------------------
  {
    type: "Storage",
    name: "Samsung 990 Pro 2 TB",
    storageType: "NVME",
    size: "2TB",
    image: "/images/parts/storage/990pro2tb.jpg",
    retailers: [
      { site: "Amazon", priceCents: 15999 },
      { site: "Newegg", priceCents: 15999 },
      { site: "Best Buy", priceCents: 15999 },
      { site: "Micro Center", priceCents: 5999 },
    ],
  },
  {
    type: "Storage",
    name: "Crucial P3 Plus 1 TB",
    storageType: "NVME",
    size: "1TB",
    image: "/images/parts/storage/p3plus1tb.jpg",
    retailers: [
      { site: "Amazon", priceCents: 6199 },
      { site: "Newegg", priceCents: 6199 },
    ],
  },
  {
    type: "Storage",
    name: "Western Digital WD_Black SN850X 2 TB",
    storageType: "NVME",
    size: "2TB",
    image: "/images/parts/storage/wd2tb.jpg",
    retailers: [
      { site: "Amazon", priceCents: 12999 },
      { site: "Newegg", priceCents: 14999 },
      { site: "Best Buy", priceCents: 14999 },
      { site: "Micro Center", priceCents: 14999 },
    ],
  },
  {
    type: "Storage",
    name: "Samsung 990 EVO Plus 2 TB",
    storageType: "NVME",
    size: "2TB",
    image: "/images/parts/storage/990evo2tb.jpg",
    retailers: [
      { site: "Amazon", priceCents: 15999 },
      { site: "Newegg", priceCents: 15999 },
      { site: "Best Buy", priceCents: 15999 },
      { site: "Micro Center", priceCents: 15999 },
    ],
  },
  {
    type: "Storage",
    name: "Seagate Barracuda Compute 2 TB",
    storageType: "HDD",
    size: "2TB",
    image: "/images/parts/storage/seagate2tb.jpg",
    retailers: [
      { site: "Amazon", priceCents: 6699 },
      { site: "Newegg", priceCents: 7099 },
      { site: "Best Buy", priceCents: 6499 },
      { site: "Micro Center", priceCents: 6499 },
    ],
  },
  {
    type: "Storage",
    name: "Samsung 870 Evo 1 TB",
    storageType: "SSD",
    size: "1TB",
    image: "/images/parts/storage/870evo1tb.jpg",
    retailers: [
      { site: "Amazon", priceCents: 7999 },
      { site: "Newegg", priceCents: 8499 },
      { site: "Best Buy", priceCents: 8499 },
      { site: "Micro Center", priceCents: 8499 },
    ],
  },

  // ------------------ Graphics ------------------

  {
    type: "Graphics Card",
    name: "ASRock Challenger OC Radeon RX 9060 XT 16 GB",
    memory: "16GB",
    length: 249,
    power: 160,
    image: "/images/parts/gpu/9060xt16gb.jpg",
    retailers: [
      { site: "Newegg", priceCents: 36999 },
      { site: "Micro Center", priceCents: 36999 },
    ],
  },
  {
    type: "Graphics Card",
    name: "Asus PRIME GeForce RTX 5060 Ti 16 GB",
    memory: "16GB",
    length: 304,
    power: 180,
    image: "/images/parts/gpu/5060ti16gb.jpg",
    retailers: [
      { site: "Newegg", priceCents: 42999 },
      { site: "Best Buy", priceCents: 42999 },
      { site: "Micro Center", priceCents: 42999 },
    ],
  },
  {
    type: "Graphics Card",
    name: "ASRock Steel Legend Radeon RX 9070 XT 16 GB",
    memory: "16GB",
    length: 298,
    power: 304,
    image: "/images/parts/gpu/9070xt16gb.jpg",
    retailers: [
      { site: "Newegg", priceCents: 69999 },
      { site: "Micro Center", priceCents: 69999 },
    ],
  },
  {
    type: "Graphics Card",
    name: "MSI VENTUS 3X OC GeForce RTX 5070 Ti 16 GB",
    memory: "16GB",
    length: 303,
    power: 300,
    image: "/images/parts/gpu/5070ti16gb.jpg",
    retailers: [
      { site: "Newegg", priceCents: 78999 },
      { site: "Best Buy", priceCents: 79999 },
      { site: "Micro Center", priceCents: 78999 },
    ],
  },
  {
    type: "Graphics Card",
    name: "PNY OC GeForce RTX 5080 16 GB",
    memory: "16GB",
    length: 329,
    power: 360,
    image: "/images/parts/gpu/508016gb.jpg",
    retailers: [
      { site: "Amazon", priceCents: 99999 },
      { site: "Best Buy", priceCents: 99999 },
      { site: "Newegg", priceCents: 99999 },
      { site: "Micro Center", priceCents: 99999 },
    ],
  },
  {
    type: "Graphics Card",
    name: "Zotac GAMING SOLID OC GeForce RTX 5090 32 GB",
    memory: "32GB",
    length: 330,
    power: 575,
    image: "/images/parts/gpu/509032gb.jpg",
    retailers: [
      { site: "Amazon", priceCents: 36999 },
      { site: "Micro Center", priceCents: 36999 },
    ],
  },

  // ------------------ Power Supply ------------------

  {
    type: "Power Supply",
    name: "Corsair RM1000e 1000 W Fully Modular ATX Power Supply",
    wattage: 1000,
    rating: "Gold",
    modular: "Yes",
    size: "ATX",
    image: "/images/parts/psu/rm1000e.jpg",
    retailers: [
      { site: "Amazon", priceCents: 14999 },
      { site: "Newegg", priceCents: 14999 },
      { site: "Best Buy", priceCents: 14999 },
    ],
  },
  {
    type: "Power Supply",
    name: "Cooler Master V850 SFX 850 W Fully Modular SFX Power Supply",
    wattage: 850,
    rating: "Gold",
    modular: "Yes",
    size: "SFX",
    image: "/images/parts/psu/v850sfx.jpg",
    retailers: [
      { site: "Amazon", priceCents: 16399 },
      { site: "Newegg", priceCents: 15499 },
    ],
  },
  {
    type: "Power Supply",
    name: "MSI MAG A750GL 750 W Fully Modular ATX Power Supply",
    wattage: 750,
    rating: "Gold",
    modular: "Yes",
    size: "ATX",
    image: "/images/parts/psu/a750gl.jpg",
    retailers: [
      { site: "Amazon", priceCents: 9999 },
      { site: "Newegg", priceCents: 9999 },
      { site: "Best Buy", priceCents: 9999 },
    ],
  },
  {
    type: "Power Supply",
    name: "Corsair RM850e 850 W Fully Modular ATX Power Supply",
    wattage: 850,
    rating: "80+ Gold",
    modular: "Yes",
    size: "ATX",
    image: "/images/parts/psu/rm850e.jpg",
    retailers: [
      { site: "Amazon", priceCents: 11499 },
      { site: "Newegg", priceCents: 11999 },
      { site: "Best Buy", priceCents: 11499 },
    ],
  },
  {
    type: "Power Supply",
    name: "Asus ROG Strix 1000 W Fully Modular ATX Power Supply",
    wattage: 1000,
    rating: "Platinum",
    modular: "Yes",
    size: "ATX",
    image: "/images/parts/psu/asus1000.jpg",
    retailers: [
      { site: "Amazon", priceCents: 11499 },
      { site: "Newegg", priceCents: 11999 },
      { site: "Best Buy", priceCents: 11499 },
    ],
  },
  {
    type: "Power Supply",
    name: "Corsair SF1000 1000 W Fully Modular SFX Power Supply",
    wattage: 1000,
    rating: "Platinum",
    modular: "Yes",
    size: "SFX",
    image: "/images/parts/psu/sf1000.jpg",
    retailers: [
      { site: "Amazon", priceCents: 26249 },
      { site: "Newegg", priceCents: 23999 },
    ],
  },

  // ------------------ Cases ------------------
  // ATX
  {
    type: "Case",
    name: "Corsair 3500X ARGB ATX Mid Tower Case",
    size: "ATX",
    maxcoolersize: 360,
    aio: true,
    gpu: 410,
    image: "/images/parts/case/corsairATX.jpg",
    retailers: [
      { site: "Amazon", priceCents: 10499 },
      { site: "Newegg", priceCents: 10499 },
      { site: "Best Buy", priceCents: 11999 },
    ],
  },
  {
    type: "Case",
    name: "NZXT H5 Flow ATX Mid Tower Case",
    size: "ATX",
    maxcoolersize: 360,
    aio: true,
    gpu: 410,
    image: "/images/parts/case/nzxtATX.jpg",
    retailers: [
      { site: "Amazon", priceCents: 8999 },
      { site: "Newegg", priceCents: 9899 },
      { site: "Best Buy", priceCents: 9499 },
    ],
  },
  // MicroATX
  {
    type: "Case",
    name: "Fractal Design Pop Mini Air MicroATX Mid Tower Case",
    size: "MATX",
    maxcoolersize: 240,
    aio: true,
    gpu: 365,
    image: "/images/parts/case/fractalMATX.jpg",
    retailers: [
      { site: "Amazon", priceCents: 12079 },
      { site: "Newegg", priceCents: 11199 },
    ],
  },
  {
    type: "Case",
    name: "Lian Li A3-mATX MicroATX Mini Tower Case",
    size: "MATX",
    maxcoolersize: 360,
    aio: true,
    gpu: 415,
    image: "/images/parts/case/lianliMATX.jpg",
    retailers: [
      { site: "Amazon", priceCents: 8999 },
      { site: "Newegg", priceCents: 8999 },
    ],
  },
  // MiniITX
  {
    type: "Case",
    name: "Fractal Design Terra Mini ITX Desktop Case",
    size: "ITX",
    maxcoolersize: 77,
    aio: false,
    gpu: 322,
    image: "/images/parts/case/fractalITX.jpg",
    retailers: [
      { site: "Amazon", priceCents: 17999 },
      { site: "Newegg", priceCents: 21198 },
      { site: "Best Buy", priceCents: 18599 },
    ],
  },
  {
    type: "Case",
    name: "Lian Li A4-H20 X4 Mini ITX Desktop Case",
    size: "ITX",
    maxcoolersize: 240,
    aio: true,
    gpu: 322,
    image: "/images/parts/case/lianliITX.jpg",
    retailers: [
      { site: "Amazon", priceCents: 15490 },
      { site: "Newegg", priceCents: 15499 },
    ],
  },
];
